Update script

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -16,14 +16,19 @@ admin=$(ynh_app_setting_get "$app" admin)
 is_public=$(ynh_app_setting_get "$app" is_public)
 language=$(ynh_app_setting_get "$app" language)
 
-# Remove trailing "/" for next commands
-path=${path%/}
+CHECK_PATH	# Vérifie et corrige la syntaxe du path.
+
+# Check if admin is not null
+if [[ "$admin" = "" || "$is_public" = "" || "$language" = "" ]]; then
+    echo "Unable to upgrade, please contact support"
+    exit 1
+fi
 
 root_pwd=$(sudo cat /etc/yunohost/mysql)
 
-final_path=/var/www/spip
+final_path=/var/www/$app
 
-db_name=spip
+db_name=$app
 
 # Check if admin is not null
 if [[ "$admin_spip" = "" || "$is_public" = "" || "$language" = "" ]]; then
@@ -38,7 +43,7 @@ sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
 
 if [ $is_public = "Yes" ];
 then
-	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/spip.conf
+	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/$app.conf
 	# grep -q "define('FORCE_SSL_ADMIN', true);" $final_path/wp-config.php
 	# if [[ ! $? -eq 0 ]];
 	# then
@@ -47,16 +52,16 @@ then
 	#     sudo sed -i "s@//define('FORCE_SSL_ADMIN@define('FORCE_SSL_ADMIN@g" $final_path/config/connect.php
 	# fi
 else
-	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/spip.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 fi
 
 # If app is public, add url to SSOWat conf as skipped_uris
 if [[ $is_public -eq 1 ]]; then
 	# See install script
 	ynh_app_setting_set "$app" unprotected_uris "/"
-	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/spip.conf
+	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/$app.conf
 else
-	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/spip.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 fi
 
 # Reload Nginx
